version: "2"

services:

  varnish:
    build: .
    depends_on:
    - haproxy
    ports:
    - "80:6081"
    - "6082:6082"
    environment:
      BACKENDS: "haproxy"
      BACKENDS_PORT: "5000"
      BACKENDS_PROBE_ENABLED: "false"
      DNS_ENABLED: "true"
      CACHE_SIZE: 1G

  haproxy:
    image: eeacms/haproxy
    depends_on:
    - webapp
    ports:
    - "5000:5000"
    - "1936:1936"
    environment:
      BACKENDS: webapp
      BACKENDS_PORT: 8080

  webapp:
    image: eeacms/hello
    ports:
    - "8080:8080"
    environment:
      PORT: 8080
