version: '2'

services:

  varnish:
    #image: eeacms/varnish
    build: .
    ports:
    - "80:8888"
    depends_on:
    - haproxy
    environment:
      VARNISH_BACKEND_PORT: 5000
      VARNISH_BACKEND_HOST: haproxy
      VARNISH_MEMORY: 512M

  haproxy:
    image: eeacms/haproxy:1.6
    environment:
      COOKIES_ENABLED: 'True'
      BACKENDS: localhost
      BACKENDS_PORT: 80
      DNS_ENABLED: 'True'
      TZ: Europe/Copenhagen
