version: "2"

services:

  varnish:
    image: eeacms/varnish-emrt-necd:1.0
    depends_on:
    - haproxy
    ports:
    - "80:80"
    environment:
      VARNISH_BACKEND_PORT: 5000
      VARNISH_BACKEND_HOST: haproxy
      VARNISH_MEMORY: 512M

  haproxy:
    image: eeacms/haproxy
    depends_on:
    - webapp
    ports:
    - "5000:5000"
    - "1936:1936"
    environment:
      BACKENDS: webapp
      BACKENDS_PORT: 8080

  webapp:
    image: eeacms/hello
    ports:
    - "8080:8080"
    environment:
      PORT: 8080
